export const SERVERS_MAP = {
  0: [
    "n00dles",
    "foodnstuff",
    "sigma-cosmetics",
    "joesguns",
    "hong-fang-tea",
    "harakiri-sushi",
    "nectar-net",
  ],
  1: ["iron-gym", "zer0", "CSEC", "max-hardware", "neo-net"],
  2: [
    "phantasy",
    "omega-net",
    "silver-helix",
    "crush-fitness",
    "avmnite-02h",
    "the-hub",
    "johnson-ortho",
  ],
  3: [
    "comptek",
    "netlink",
    "rothman-uni",
    "summit-uni",
    "catalyst",
    "I.I.I.I",
    "millenium-fitness",
    "rho-construction",
  ],
  4: [
    "syscore",
    "lexo-corp",
    "aevum-police",
    "alpha-ent",
    "global-pharm",
    "snap-fitness",
    "unitalife",
    "univ-energy",
    "zb-def",
    "nova-med",
    "applied-energetics",
    "run4theh111z",
    ".",
  ],
  5: [
    // "darkweb",
    "zb-institute",
    "aerocorp",
    "galactic-cyber",
    "deltaone",
    "omnia",
    "icarus",
    "solaris",
    "defcomm",
    "zeus-med",
    "infocomm",
    "taiyang-digital",
    "microdyne",
    "titan-labs",
    "fulcrumtech",
    "vitalife",
    "stormtech",
    "helios",
    "kuai-gong",
    "omnitek",
    "4sigma",
    "b-and-a",
    "blade",
    "clarkinc",
    "nwo",
    "powerhouse-fitness",
    "megacorp",
    "ecorp",
    "The-Cave",
    "fulcrumassets",
  ],
};

export const SERVERS = Object.values(SERVERS_MAP).flat();

export enum Ports {
  STATUS = 1,
}

export const NODES = [
  "alethkar",
  "jah-keved",
  "herdaz",
  "emul",
  "azir",
  "thaylenah",
  "shinovar",
  "triax",
  "greater-hexi",
  "marat",
  "reshi-isles",
  "tukar",
  "yulay",
  "marabethia",
  "babatharnam",
  "desh",
  "frostlands",
  "yezier",
  "alm",
  "tashikk",
  "liafor",
  "steen",
  "aimia",
  "iri",
  "rira",
];
